package vista;

import dao.DaoUsuario;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.time.*;
import java.util.ArrayList;

import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.border.LineBorder;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import modelo.DB;
import modelo.Usuario;

import utiles.Utiles;

public class PanelTablaUsuarios extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    private JTable tablaUsuarios;
    private DefaultTableModel cuadricula;
    private int numColumns;
    private String[] nombreColumnas;
    private ArrayList<Usuario> listaUsuarios;

    private JScrollPane scrollPane;

    /**
     * Creates new form PanelTablaUsuarios
     */
    public PanelTablaUsuarios() {

        this.setLayout(new BorderLayout());

        this.cuadricula = new DefaultTableModel();        
        this.tablaUsuarios = new JTable(cuadricula);

        // Personalización de JTable //
        // Se le da un color por defecto, pero se cambiará
        // Esto se hace por si falla la decodificación del color en HEX
        Color colorLineaBordeTabla = new Color(0, 0, 0);
        Color colorBackgroundTabla = new Color(255, 255, 255);

        // Se intenta decodificar el color en HEX
        try {
            colorLineaBordeTabla = Color.decode("#" + Utiles.COLOR_MARRON2);
            colorBackgroundTabla = Color.decode("#" + Utiles.COLOR_ROJO2);
        } catch (NumberFormatException ex) {
            System.out.println("Error al intentar decodificar un color en HEX");
            ex.printStackTrace();

        }

        this.tablaUsuarios.setBorder(new LineBorder(colorLineaBordeTabla));
        this.tablaUsuarios.setBackground(colorBackgroundTabla);

        // Añadir COMPONENTES al PANEL        
        scrollPane = new JScrollPane(this.tablaUsuarios);
        this.tablaUsuarios.setFillsViewportHeight(true);
//        this.tablaUsuarios.setTableHeader(new JTableHeader());
        this.add(scrollPane, BorderLayout.CENTER);
        this.add(this.tablaUsuarios.getTableHeader(), BorderLayout.PAGE_START);

        //////////////////////////////////////////
        // Añadimos los datos a la tabla
        actualizaTabla(tablaUsuarios);

    }

    public void actualizaTabla(JTable tablaUsuarios) {

        // Clase que nos gestiona los métodos para comunicarnos con la BD
        DaoUsuario daoUsuario = new DaoUsuario();

        nombreColumnas = new String[]{"ID",
            "Apellido1", "Apellido2",
            "Nombre", "Fecha de Nacimiento"};

        cuadricula.addColumn(nombreColumnas[0]);
        cuadricula.addColumn(nombreColumnas[1]);
        cuadricula.addColumn(nombreColumnas[2]);
        cuadricula.addColumn(nombreColumnas[3]);
        cuadricula.addColumn(nombreColumnas[4]);

        numColumns = nombreColumnas.length;

        // Limpiamos la tabla antes de añadir los datos de la BD
        while (cuadricula.getRowCount() > 0) {
            cuadricula.removeRow(0);
        }

        listaUsuarios = daoUsuario.leerUsuarios();
        for (Usuario u : listaUsuarios) {

            Object datosFila[] = new Object[numColumns];

            datosFila[0] = u.getId();
            datosFila[1] = u.getApellido1();
            datosFila[2] = u.getApellido2();
            datosFila[3] = u.getNombre();
            datosFila[4] = u.getFechaNacimiento();

            cuadricula.addRow(datosFila);
        }

        tablaUsuarios.setModel(cuadricula);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
