/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.VentanaTablaUsuariosControlador;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import utiles.Utiles;

/**
 *
 * @author profesor
 */
public class VentanaTablaUsuarios extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;
    private JPanel panelTablaUsuarios;

    /**
     * Creates new form VentanaTablaUsuarios
     */
    public VentanaTablaUsuarios() {
        this.setModal(true);
        this.setTitle(Utiles.TITULO_VENTANA_USUARIOS);

        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setBounds(100, 100, 450, 300);

        // Que no se pueda redimensionar
        this.setResizable(false);

        panelTablaUsuarios = new PanelTablaUsuarios();
        panelTablaUsuarios.setBorder(new EmptyBorder(5, 5, 5, 5));

//        JTable tablaUsuarios = panelTablaUsuarios.getTablaUsuarios();
//        scrollPane.add();
//        this.add(scrollPane);
        this.setContentPane(panelTablaUsuarios);

        this.setLocationRelativeTo(null);
        
        // Gestión de Eventos de la VentanaTablaUsuario
        this.addWindowListener(new VentanaTablaUsuariosControlador(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
