/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.VentanaAccionesUsuarioControlador;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author profesor
 */
public class VentanaAccionesUsuario extends javax.swing.JFrame {

    /**
     * Creates new form VentanaUsuario
     */
    public VentanaAccionesUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAccionesUsuario = new javax.swing.JPanel();
        jLabelID = new javax.swing.JLabel();
        jLabelApellido1 = new javax.swing.JLabel();
        jLabelApellido2 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelFechaNacimiento = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldFechaNacimiento = new javax.swing.JTextField();
        jLabelFormatoFecha = new javax.swing.JLabel();
        jMenuBarUsuario = new javax.swing.JMenuBar();
        jMenuAcciones = new javax.swing.JMenu();
        jMenuItemCrear = new javax.swing.JMenuItem();
        jMenuItemLeer = new javax.swing.JMenuItem();
        jMenuItemActualizar = new javax.swing.JMenuItem();
        jMenuItemBorrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acciones Usuario");
        setName("ventanaAccionesUsuario"); // NOI18N

        jLabelID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelID.setText("ID");

        jLabelApellido1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelApellido1.setText("Apellido 1");

        jLabelApellido2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelApellido2.setText("Apellido 2");

        jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNombre.setText("Nombre");

        jLabelFechaNacimiento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFechaNacimiento.setText("Fecha Nacimiento");

        jTextFieldID.setEditable(false);

        jLabelFormatoFecha.setText("Formato de fecha: 2023-12-19");

        javax.swing.GroupLayout jPanelAccionesUsuarioLayout = new javax.swing.GroupLayout(jPanelAccionesUsuario);
        jPanelAccionesUsuario.setLayout(jPanelAccionesUsuarioLayout);
        jPanelAccionesUsuarioLayout.setHorizontalGroup(
            jPanelAccionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccionesUsuarioLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanelAccionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelApellido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelApellido2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelAccionesUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAccionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFormatoFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNombre)
                    .addComponent(jTextFieldApellido1)
                    .addComponent(jTextFieldApellido2)
                    .addGroup(jPanelAccionesUsuarioLayout.createSequentialGroup()
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldFechaNacimiento))
                .addGap(57, 57, 57))
        );
        jPanelAccionesUsuarioLayout.setVerticalGroup(
            jPanelAccionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccionesUsuarioLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanelAccionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAccionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelApellido1)
                    .addComponent(jTextFieldApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAccionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellido2)
                    .addComponent(jTextFieldApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAccionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAccionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaNacimiento)
                    .addComponent(jTextFieldFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFormatoFecha)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jMenuAcciones.setText("Acciones");

        jMenuItemCrear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/crear.png"))); // NOI18N
        jMenuItemCrear.setText("Crear");
        jMenuItemCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearActionPerformed(evt);
            }
        });
        jMenuAcciones.add(jMenuItemCrear);

        jMenuItemLeer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemLeer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/view.png"))); // NOI18N
        jMenuItemLeer.setText("Leer");
        jMenuItemLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLeerActionPerformed(evt);
            }
        });
        jMenuAcciones.add(jMenuItemLeer);

        jMenuItemActualizar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/update.png"))); // NOI18N
        jMenuItemActualizar.setText("Actualizar");
        jMenuItemActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemActualizarActionPerformed(evt);
            }
        });
        jMenuAcciones.add(jMenuItemActualizar);

        jMenuItemBorrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/delete.png"))); // NOI18N
        jMenuItemBorrar.setText("Borrar");
        jMenuItemBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBorrarActionPerformed(evt);
            }
        });
        jMenuAcciones.add(jMenuItemBorrar);

        jMenuBarUsuario.add(jMenuAcciones);

        setJMenuBar(jMenuBarUsuario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAccionesUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAccionesUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearActionPerformed
        // TODO add your handling code here:
        VentanaAccionesUsuarioControlador controlador = new VentanaAccionesUsuarioControlador(this);
        boolean esInsertado = controlador.insertarUsuario();
        
        if(esInsertado){
            jTextFieldApellido1.setText("");
            jTextFieldApellido2.setText("");
            jTextFieldNombre.setText("");
            jTextFieldFechaNacimiento.setText("");
        }
    }//GEN-LAST:event_jMenuItemCrearActionPerformed

    private void jMenuItemLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLeerActionPerformed
        // TODO add your handling code here:
        VentanaAccionesUsuarioControlador controlador = new VentanaAccionesUsuarioControlador(this);
        controlador.abrirVentanaTablaUsuarios();
    }//GEN-LAST:event_jMenuItemLeerActionPerformed

    private void jMenuItemActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemActualizarActionPerformed

    private void jMenuItemBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VentanaAccionesUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VentanaAccionesUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VentanaAccionesUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VentanaAccionesUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VentanaAccionesUsuario().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelApellido1;
    private javax.swing.JLabel jLabelApellido2;
    private javax.swing.JLabel jLabelFechaNacimiento;
    private javax.swing.JLabel jLabelFormatoFecha;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JMenu jMenuAcciones;
    private javax.swing.JMenuBar jMenuBarUsuario;
    private javax.swing.JMenuItem jMenuItemActualizar;
    private javax.swing.JMenuItem jMenuItemBorrar;
    private javax.swing.JMenuItem jMenuItemCrear;
    private javax.swing.JMenuItem jMenuItemLeer;
    private javax.swing.JPanel jPanelAccionesUsuario;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldFechaNacimiento;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables

    
    // GETTERS Y SETTERS
    public JLabel getjLabelApellido1() {
        return jLabelApellido1;
    }

    public void setjLabelApellido1(JLabel jLabelApellido1) {
        this.jLabelApellido1 = jLabelApellido1;
    }

    public JLabel getjLabelApellido2() {
        return jLabelApellido2;
    }

    public void setjLabelApellido2(JLabel jLabelApellido2) {
        this.jLabelApellido2 = jLabelApellido2;
    }

    public JLabel getjLabelFechaNacimiento() {
        return jLabelFechaNacimiento;
    }

    public void setjLabelFechaNacimiento(JLabel jLabelFechaNacimiento) {
        this.jLabelFechaNacimiento = jLabelFechaNacimiento;
    }

    public JLabel getjLabelID() {
        return jLabelID;
    }

    public void setjLabelID(JLabel jLabelID) {
        this.jLabelID = jLabelID;
    }

    public JLabel getjLabelNombre() {
        return jLabelNombre;
    }

    public void setjLabelNombre(JLabel jLabelNombre) {
        this.jLabelNombre = jLabelNombre;
    }

    public JMenu getjMenuAcciones() {
        return jMenuAcciones;
    }

    public void setjMenuAcciones(JMenu jMenuAcciones) {
        this.jMenuAcciones = jMenuAcciones;
    }

    public JMenuBar getjMenuBarUsuario() {
        return jMenuBarUsuario;
    }

    public void setjMenuBarUsuario(JMenuBar jMenuBarUsuario) {
        this.jMenuBarUsuario = jMenuBarUsuario;
    }

    public JMenuItem getjMenuItemActualizar() {
        return jMenuItemActualizar;
    }

    public void setjMenuItemActualizar(JMenuItem jMenuItemActualizar) {
        this.jMenuItemActualizar = jMenuItemActualizar;
    }

    public JMenuItem getjMenuItemBorrar() {
        return jMenuItemBorrar;
    }

    public void setjMenuItemBorrar(JMenuItem jMenuItemBorrar) {
        this.jMenuItemBorrar = jMenuItemBorrar;
    }

    public JMenuItem getjMenuItemCrear() {
        return jMenuItemCrear;
    }

    public void setjMenuItemCrear(JMenuItem jMenuItemCrear) {
        this.jMenuItemCrear = jMenuItemCrear;
    }

    public JMenuItem getjMenuItemLeer() {
        return jMenuItemLeer;
    }

    public void setjMenuItemLeer(JMenuItem jMenuItemLeer) {
        this.jMenuItemLeer = jMenuItemLeer;
    }

    public JPanel getjPanelAccionesUsuario() {
        return jPanelAccionesUsuario;
    }

    public void setjPanelAccionesUsuario(JPanel jPanelAccionesUsuario) {
        this.jPanelAccionesUsuario = jPanelAccionesUsuario;
    }

    public JTextField getjTextFieldApellido1() {
        return jTextFieldApellido1;
    }

    public void setjTextFieldApellido1(JTextField jTextFieldApellido1) {
        this.jTextFieldApellido1 = jTextFieldApellido1;
    }

    public JTextField getjTextFieldApellido2() {
        return jTextFieldApellido2;
    }

    public void setjTextFieldApellido2(JTextField jTextFieldApellido2) {
        this.jTextFieldApellido2 = jTextFieldApellido2;
    }

    public JTextField getjTextFieldFechaNacimiento() {
        return jTextFieldFechaNacimiento;
    }

    public void setjTextFieldFechaNacimiento(JTextField jTextFieldFechaNacimiento) {
        this.jTextFieldFechaNacimiento = jTextFieldFechaNacimiento;
    }

    public JTextField getjTextFieldID() {
        return jTextFieldID;
    }

    public void setjTextFieldID(JTextField jTextFieldID) {
        this.jTextFieldID = jTextFieldID;
    }

    public JTextField getjTextFieldNombre() {
        return jTextFieldNombre;
    }

    public void setjTextFieldNombre(JTextField jTextFieldNombre) {
        this.jTextFieldNombre = jTextFieldNombre;
    }





}
